Information:
   Display_Name: "%gangland_unique-item_phone_name%"
   Size: 54
   Type: inventory
   Open:
      Event:
         OnItemClick:
            Action: RIGHT_CLICK
         UniqueItem: phone
   Configuration:
      Line:
         Vertical: [2,8]
         Horizontal: [1,6]
      Fill: true
   Permission: "gangland.inventory.phone"

Slots:
   20:
      Item:
         Type: LEATHER_CHESTPLATE
         Color: "GREEN"
      Name: "&a&lMy Gang"
      Lore:
         - "&7Play with friends, and dominate the city!"
      OnClick:
         Inventory: phone_gang
   22:
      Item: FURNACE
      Name: "&d&lBounties"
      Lore:
         - "&7Place hits on other players!"
      OnClick:
         Inventory: phone_bounty
   24:
      Item: PAPER
      Name: "&b&lOnline Banking"
      Lore:
         - "&7Keeping your money safe!"
      OnClick:
         Inventory: phone_banking
   40:
      Item: EMERALD
      Name: "&a&lWallet"
      Lore:
         - "&e%money_symbol%%gangland_user_balance%"
