Information:
   Display_Name: "&6&lGang Members"
   Size: 54
   Type: multi-inventory
   Configuration:
      Fill: true
      Border: true
   Multi:
      Item_Source: "gang_members"
      Per_Page: 28
   Item_Template:
      Item:
         Type: PLAYER_HEAD
         Data: "%member_name%"
      Name: "&b%member_name%"
      Lore:
         - "&7Rank:&e %member_rank%"
         - "&7Contribution:&e %member_contribution%"
         - "&7Joined:&e %member_join_date%"
         - ""
         - "&7Status: %member_online_status%"
