<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.luckyraven</groupId>
        <artifactId>gangland-features</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cops-n-crooks</artifactId>

    <name>Cops N Crooks</name>

    <dependencies>
        <!-- Spigot Build (full server — needed for io.netty access) -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Local dependencies -->
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-item</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>version-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>plugin-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-weapon</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>inventory-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>shop-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-economy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-turf</artifactId>
        </dependency>

        <!-- Citizens dependency -->
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizens-main</artifactId>
        </dependency>

        <!-- XSeries dependency -->
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
        </dependency>
    </dependencies>

</project>
