Information:
   Display_Name: "&6&l%gangland_gang_name%&r gang"
   Size: 45
   Type: inventory
   Open:
      Command: "/glw gang"
      Permission: "gangland.command.gang"
   Configuration:
      Fill: true
      Border: false
   Permission: "gangland.inventory.gang_stat"
Slots:
   11:
      Item: GOLD_BLOCK
      Name: "&bBalance"
      Lore:
         - "&e%money_symbol%%gangland_gang_balance%"
      Enchanted: true
   13:
      Item: CRAFTING_TABLE
      Name: "&bID"
      Lore:
         - "&e%gangland_gang_id%"
   15:
      Item: PAPER
      Name: "&bDescription"
      Lore:
         - "&e%gangland_gang_description%"
      OnClick:
         Command: "/glw gang desc"
   19:
      Item: PLAYER_HEAD
      Name: "&bMembers"
      Lore:
         - "&a%gangland_gang_online-members-size%&7/&e%gangland_gang_members-size%"
      OnClick:
         Inventory: users_stat
   22:
      Item: BLAZE_ROD
      Name: "&bBounty"
      Lore:
         - "&e%money_symbol%%gangland_gang_bounty%"
      Enchanted: true
   25:
      Item: REDSTONE
      Name: "&bAlly"
      Lore:
         - "&e%gangland_gang_ally-size%"
      OnClick:
         Inventory: alliance_stat
   29:
      Item: WRITABLE_BOOK
      Name: "&bCreated"
      Lore:
         - "&e%gangland_gang_created%"
      Enchanted: true
   31:
      Item:
         Type: WOOL
         Color: "%gangland_gang_color%"
      Name: "&bColor"
      Lore:
         - "&e%gangland_gang_color-name%"
      OnClick:
         Command: "/glw gang color"
   33:
      Item:
         Type: BANNER
         Color: "%gangland_gang_color%"
      Name: "&bStatistics"
      Lore:
         - "&eGang stats"
      OnClick:
         Inventory: gang_stat