<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.luckyraven</groupId>
        <artifactId>gangland-infra</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>gangland-domain</artifactId>

    <name>Gangland Domain</name>

    <dependencies>
        <!-- Local dependencies -->
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>plugin-common</artifactId>
        </dependency>
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>plugin-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>gangland-core</artifactId>
        </dependency>
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>gangland-economy</artifactId>
        </dependency>
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>inventory-api</artifactId>
        </dependency>
        <dependency>
            <groupId>me.luckyraven</groupId>
            <artifactId>scoreboard-api</artifactId>
        </dependency>

        <!-- XSeries -->
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
        </dependency>

        <!-- NBTAPI -->
        <dependency>
            <groupId>de.tr7zw</groupId>
            <artifactId>item-nbt-api-plugin</artifactId>
        </dependency>

        <!-- Vault (soft) -->
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
        </dependency>
    </dependencies>

</project>
