<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.luckyraven</groupId>
        <artifactId>gangland_warfare</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>gangland-impl</artifactId>
    <packaging>jar</packaging>

    <name>Gangland</name>

    <dependencies>
        <!-- Bukkit/Spigot/Paper builds (start) -->

        <!-- Spigot Build -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Bukkit/Spigot/Paper builds (end) -->

        <!-- Important local dependencies (start) -->
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>version-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>hologram-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-weapon</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>inventory-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>plugin-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>plugin-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>scoreboard-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>sign-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>lootchest-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>shop-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>cops-n-crooks</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-economy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-gadget</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-turf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.luckyraven</groupId>
            <artifactId>gangland-mail</artifactId>
        </dependency>
        <!-- Important local dependencies (end) -->

        <!-- Compile level dependencies (start) -->

        <!-- AnvilGUI -->
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <scope>compile</scope>
        </dependency>

        <!-- bStats -->
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
        </dependency>

        <!-- XSeries -->
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <scope>compile</scope>
        </dependency>

        <!-- reflections -->
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>

        <!-- Compile level dependencies (end) -->

        <!-- Required plugins dependencies (start) -->

        <!-- NBTAPI -->
        <dependency>
            <groupId>de.tr7zw</groupId>
            <artifactId>item-nbt-api-plugin</artifactId>
        </dependency>

        <!-- Required plugins dependencies (end) -->

        <!-- Soft plugins dependencies (start) -->

        <!-- PlaceholderAPI -->
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
        </dependency>

        <!-- Vault -->
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
        </dependency>

        <!-- CitizenAPI -->
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizens-main</artifactId>
        </dependency>

        <!-- ViaVersion -->
        <dependency>
            <groupId>com.viaversion</groupId>
            <artifactId>viaversion-api</artifactId>
        </dependency>

        <!-- Soft plugins dependencies (end) -->

        <!-- Test dependencies (start) -->

        <!-- Junit -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>

        <!-- Mocking -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>

        <!-- Test dependencies (end) -->

    </dependencies>

</project>
